version: '3.8'

services:
  ip-tracker:
    build: .
    container_name: flask-ip-tracker
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ip-tracker-network

networks:
  ip-tracker-network:
    driver: bridge

volumes:
  data:
    driver: local